#!/usr/bin/env python3
from utils.api import create_jira_issue, get_jira_instance, show_my_current_issues
from utils.arg_parser import get_parser


def main():

    parser = get_parser()
    args = parser.parse_args()

    jira = get_jira_instance()
    if args.command == "create":
        description = args.description if args.description else args.summary
        create_jira_issue(
            jira,
            args.summary,
            description,
            args.labels,
            args.assignee,
            args.story_points,
        )
    elif args.command == "show":
        show_my_current_issues(jira, args.username)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
