#!/bin/bash


# DragonFly Settings Uncomment to enable dragonfly if it is available on server
# export NO_PROXY=''
# export no_proxy=''
# export HTTPS_PROXY=127.0.0.1:65001
export SINGULARITY_CACHEDIR=/tmp/singularity.`id --u --name`


args=("$@")
# # Example using a docker image uploaded to harbor
# exec singularity exec docker://amr-registry.caas.intel.com/ec-fieldengineering/ijira:latest python3 /app/ijira ${args[@]}


# # Example using a singularity image uploaded to harbor
# exec /usr/bin/singularity exec -B /nfs,/etc/krb5.conf,/usr oras://amr-registry.caas.intel.com/ec-fieldengineering/agscli:sles15_sif /usr/intel/pkgs/python3/3.10.8/bin/python3 /app/ags.py ${args[@]}


# Example with a prebuilt sinularity image locally
if [ ! -f ijira.sif ]; then
   singularity build ijira.sif docker://amr-registry.caas.intel.com/ec-fieldengineering/ijira:latest
fi
exec singularity exec ijira.sif python3 /app/ijira ${args[@]}
